# Generated by Django 6.0.7 on 2026-07-19 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Common name or technical name of the disease (e.g. Apple___Apple_scab)', max_length=200, unique=True)),
                ('crop', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Detailed symptoms of the disease')),
                ('possible_causes', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_knowledge_disease',
                'ordering': ['crop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measure', models.TextField()),
                ('timing', models.CharField(blank=True, help_text='e.g. Pre-planting, Post-harvest', max_length=100, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventions', to='disease_diagnosis.disease')),
            ],
            options={
                'db_table': 'ai_knowledge_prevention',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='disease_diagnosis.disease')),
            ],
            options={
                'db_table': 'ai_knowledge_reference',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Organic', 'Organic'), ('Chemical', 'Chemical'), ('Biological', 'Biological')], max_length=50)),
                ('method', models.TextField()),
                ('application_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_precautions', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='disease_diagnosis.disease')),
            ],
            options={
                'db_table': 'ai_knowledge_treatment',
            },
        ),
    ]
