# Generated by Django 6.0.7 on 2026-07-19 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_date', models.DateField(verbose_name='sample date')),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='nitrogen (N) mg/kg')),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='phosphorus (P) mg/kg')),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='potassium (K) mg/kg')),
                ('organic_carbon', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='organic carbon (%)')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH level')),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='moisture content (%)')),
                ('electrical_conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='electrical conductivity (dS/m)')),
                ('texture', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('silt', 'Silt'), ('loam', 'Loam'), ('sandy_loam', 'Sandy Loam'), ('clay_loam', 'Clay Loam'), ('other', 'Other')], max_length=20, verbose_name='soil texture')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks / lab notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('farm', models.ForeignKey(help_text='Farm from which the sample was taken.', on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='farms.farm')),
            ],
            options={
                'verbose_name': 'soil sample',
                'verbose_name_plural': 'soil samples',
                'ordering': ['-sample_date'],
            },
        ),
    ]
