# Generated by Django 6.0.7 on 2026-07-19 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100, unique=True, verbose_name='crop name')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='scientific name')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('all_season', 'All Season')], default='all_season', max_length=20, verbose_name='growing season')),
                ('category', models.CharField(choices=[('cereal', 'Cereal'), ('pulse', 'Pulse'), ('oilseed', 'Oilseed'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('fiber', 'Fiber'), ('spice', 'Spice'), ('other', 'Other')], default='other', max_length=20, verbose_name='crop category')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='typical duration in days')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('optimal_temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='optimal min temperature (°C)')),
                ('optimal_temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='optimal max temperature (°C)')),
                ('optimal_rainfall_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='optimal min rainfall (mm)')),
                ('optimal_rainfall_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='optimal max rainfall (mm)')),
                ('optimal_humidity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='optimal min humidity (%)')),
                ('optimal_humidity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='optimal max humidity (%)')),
                ('optimal_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='optimal min pH')),
                ('optimal_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='optimal max pH')),
                ('water_requirement', models.TextField(blank=True, verbose_name='water requirement description')),
                ('growth_stages', models.JSONField(blank=True, default=list, help_text='JSON list of growth stages', verbose_name='growth stages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'crop',
                'verbose_name_plural': 'crops',
                'ordering': ['crop_name'],
            },
        ),
    ]
