# Generated by Django 6.0.7 on 2026-07-19 15:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID v4 primary key for this farm profile.', primary_key=True, serialize=False)),
                ('farm_name', models.CharField(help_text='Descriptive name or title of the farm parcel.', max_length=255, verbose_name='farm name')),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='farms/%Y/%m/', verbose_name='farm profile image')),
                ('area', models.DecimalField(decimal_places=2, help_text='Total surface area of the farm (must be greater than 0).', max_digits=10, verbose_name='total area')),
                ('unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('sq_meters', 'Square Meters')], default='acres', max_length=20, verbose_name='area unit')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate ranging from -90.0 to 90.0.', max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate ranging from -180.0 to 180.0.', max_digits=9, null=True, verbose_name='longitude')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state / province')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='district / county')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='village / locality')),
                ('address', models.TextField(blank=True, verbose_name='detailed physical address')),
                ('water_source', models.CharField(choices=[('canal', 'Canal Irrigation'), ('tube_well', 'Tube Well / Borewell'), ('open_well', 'Open Well'), ('rainfed', 'Rainfed / Monsoon'), ('drip_irrigation', 'Drip Irrigation System'), ('sprinkler', 'Sprinkler Irrigation System'), ('other', 'Other / Mixed')], default='rainfed', max_length=30, verbose_name='primary water source')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive / Fallow'), ('archived', 'Archived')], db_index=True, default='active', max_length=30, verbose_name='operational status')),
                ('notes', models.TextField(blank=True, verbose_name='additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('owner', models.ForeignKey(help_text='User account (farmer/manager) that owns this farm.', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID v4 primary key for this farm crop cycle.', primary_key=True, serialize=False)),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='crop variety / seed strain')),
                ('sowing_date', models.DateField(verbose_name='sowing / planting date')),
                ('expected_harvest_date', models.DateField(blank=True, null=True, verbose_name='expected harvest date')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='actual harvest date')),
                ('area_allocated', models.DecimalField(decimal_places=2, help_text='Land area allocated to this specific crop cycle (in Farm unit).', max_digits=10, verbose_name='area allocated')),
                ('status', models.CharField(choices=[('sown', 'Sown / Planted'), ('vegetative', 'Vegetative Stage'), ('flowering', 'Flowering Stage'), ('fruiting', 'Fruiting / Podding Stage'), ('harvested', 'Harvested'), ('failed', 'Failed / Damaged'), ('archived', 'Archived')], db_index=True, default='sown', max_length=30, verbose_name='crop cycle status')),
                ('estimated_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated yield (kg)')),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='actual yield (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='cultivation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('crop', models.ForeignKey(help_text='Global Crop Master reference.', on_delete=django.db.models.deletion.PROTECT, related_name='farm_cultivations', to='crops.crop')),
                ('farm', models.ForeignKey(help_text='Farm parcel where this crop is being cultivated.', on_delete=django.db.models.deletion.CASCADE, related_name='farm_crops', to='farms.farm')),
            ],
            options={
                'verbose_name': 'farm crop',
                'verbose_name_plural': 'farm crops',
                'ordering': ['-sowing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID v4 primary key for this activity log entry.', primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('sowing', 'Sowing / Planting'), ('irrigation', 'Irrigation / Watering'), ('fertilizer_application', 'Fertilizer / Manure Application'), ('pesticide_application', 'Pesticide / Herbicide Application'), ('weeding', 'Weeding / Cleaning'), ('soil_testing', 'Soil Sampling / Testing'), ('harvesting', 'Harvesting'), ('observation', 'Field Observation / Scouing'), ('general_maintenance', 'General Maintenance / Repair'), ('other', 'Other Activity')], db_index=True, default='observation', max_length=40, verbose_name='activity type')),
                ('activity_date', models.DateField(default=django.utils.timezone.now, verbose_name='activity date')),
                ('title', models.CharField(max_length=255, verbose_name='activity title')),
                ('description', models.TextField(blank=True, verbose_name='activity details')),
                ('cost_incurred', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost incurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.farm')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('farm_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='farms.farmcrop')),
            ],
            options={
                'verbose_name': 'farm activity',
                'verbose_name_plural': 'farm activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID v4 primary key for this farm image.', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='farm_images/%Y/%m/', verbose_name='image file')),
                ('image_type', models.CharField(choices=[('general', 'General Farm View'), ('crop_progress', 'Crop Growth Progress'), ('soil_condition', 'Soil Condition'), ('pest_disease_observation', 'Pest / Disease Observation'), ('harvest', 'Harvesting Stage'), ('other', 'Other / Miscellaneous')], db_index=True, default='general', max_length=40, verbose_name='image category')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='image caption')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='captured timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farms.farm')),
                ('farm_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='farms.farmcrop')),
            ],
            options={
                'verbose_name': 'farm image',
                'verbose_name_plural': 'farm images',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['owner', 'status', 'is_deleted'], name='farms_farm_owner_i_bc1ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['state', 'district'], name='farms_farm_state_b2eb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='farmcrop',
            index=models.Index(fields=['farm', 'status', 'is_deleted'], name='farms_farmc_farm_id_622f49_idx'),
        ),
        migrations.AddIndex(
            model_name='farmcrop',
            index=models.Index(fields=['crop', 'sowing_date'], name='farms_farmc_crop_id_c81534_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['farm', 'activity_type', 'is_deleted'], name='farms_farma_farm_id_b6f364_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['activity_date'], name='farms_farma_activit_327ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='farmimage',
            index=models.Index(fields=['farm', 'image_type', 'is_deleted'], name='farms_farmi_farm_id_415756_idx'),
        ),
    ]
