# Generated by Django 5.1.15 on 2026-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("prediction", "Prediction"),
                    ("recommendation", "Recommendation"),
                    ("system", "System"),
                    ("alert", "Alert"),
                ],
                default="system",
                max_length=20,
                verbose_name="category",
            ),
        ),
    ]
