# Generated by Django 6.0.7 on 2026-07-19 15:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="snapshot date and time")),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="temperature (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="humidity (%)",
                    ),
                ),
                (
                    "rainfall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="rainfall (mm)",
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="wind speed (km/h)",
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="atmospheric pressure (hPa)",
                    ),
                ),
                (
                    "cloud_cover",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="cloud cover (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Farm this weather snapshot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "weather snapshot",
                "verbose_name_plural": "weather snapshots",
                "ordering": ["-date"],
            },
        ),
    ]
